### PR TITLE
Revert "switch to .NET 8"

### PR DESCRIPTION
**Pull request by kuylar**
Reverts lighttube-org/LightTube#120

### CODE REVIEW

**Comment by InFTord** [comment]
fuck you i am gonna merge this one, not you

**Comment by kuylar** [comment]
fuck YOU

**Comment by kuylar** [comment]
im adding review requirements

**Comment by InFTord** [comment]
no, fuck ***YOU.***

**Comment by OoLunar** [comment]
Tony? Ezekiel?

**Pull request merged**
